# Generated by Django 3.2.3 on 2021-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('item_name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=0)),
                ('receive_quantity', models.IntegerField(default=0)),
                ('receive_by', models.CharField(max_length=50)),
                ('issue_quantity', models.IntegerField(default=0)),
                ('issue_by', models.CharField(max_length=50)),
                ('issue_to', models.CharField(max_length=50)),
                ('reorder_level', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
